Poll/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Poll.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^sllod/', include('sllod.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r"^account/", include("account.urls")),
    url(r'^', include("home.urls")),
    
)

home/urls.py
from django.conf.urls import patterns, url

from home import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
)

sllod/urls.py
from django.conf.urls import patterns, url

from sllod import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
   # url(r'^create', views.add_poll, name='poll'),
    url(r'^add_poll/$', views.add_poll, name='add_poll'),
    url(r'^create_poll/$', views.create_poll, name='create_poll'),
    url(r'^get_polls/$', views.ajax_poll_list, name='get_poll'),
    url(r'^option_vote/$', views.option_vote, name='vote_poll'),
)

home/models.py
from django.db import models

# Create your models here.

sllod/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User

'''
Poll Class
'''
class Poll(models.Model):
    message = models.CharField(max_length=200)
    created_at = models.DateTimeField('date created')
    created_by = models.ForeignKey(User)
    share = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    '''
    def __init__(self):
        created_by = datetime.datetime.today()
    '''
    def __str__(self):
        
        return self.message
    
    def was_published_recently(self):
        return self.created_at >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'created_at'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?' 
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.created_at = datetime.datetime.today()
            #self.share = 100;
            super(Poll, self).save(*args, **kwargs)
            self.make_option()
        else:
            super(Poll, self).save(*args, **kwargs)
    
    def make_option(self):
        words = self.message.split()
        for word in words:
            if word.find('#') != -1:
                option = Option    
                option.objects.create(poll = self, option_text = word)
'''
Option Class
'''            
class Option(models.Model):
    poll = models.ForeignKey(Poll)
    option_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    percentage = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    
    def __str__(self):
        return self.option_text
'''
OptionVote Class
'''       
class OptionVote(models.Model):
    poll = models.ForeignKey(Poll)
    option = models.ForeignKey(Option)
    created_by = models.ForeignKey(User)
    has_changed = models.BooleanField()
    created_at = models.DateTimeField('date created')
    
    class Meta:
        unique_together = ("poll", "option", "created_by")
    
    

home/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseServerError
from sllod.forms import PollForm
from sllod.models import Poll, Option, OptionVote
from django.utils import timezone
from django.db import IntegrityError
def index(request):
    latest_poll_list = Poll.objects.order_by('-created_at')[:15]
    if request.POST:
        form = PollForm(request.POST)
        if form.is_valid():

            # commit=False means the form doesn't save at this time.
            # commit defaults to True which means it normally saves.
            
            model_instance = form.save(commit=False)
            model_instance.created_by = request.user
            model_instance.created_at = timezone.now()
            model_instance.save()
            if request.is_ajax():
                return render(request, "polls/poll_list.html", {'latest_poll_list': latest_poll_list})
    else:
        form = PollForm()
        
    return render(request, "home/index.html", {'form': form, 'latest_poll_list': latest_poll_list})
    #return render(request, 'home/index.html')

home/templates/home/index.html
<!DOCTYPE html>
{% load staticfiles %} 
{% load account_tags %}

<link href="{% static  "bootstrap/css/bootstrap.css" %}" rel="stylesheet" />
<link href="{% static  "bootswatch/css/bootstrap.css" %}" rel="stylesheet" />
<link href="{% static  "bootswatch/css/bootswatch.min.css" %}" rel="stylesheet" />
<link href="{% static  "css/home.css" %}" rel="stylesheet"/>
<script src="{% static  "js/jquery-1.11.0.js" %}"></script>
<script src="{% static  "bootstrap/js/bootstrap.js" %}"></script>
<script src="{% static  "bootswatch/js/bootswatch.js" %}"></script>
<script src="{% static  "js/poll.js" %}"></script>
		
		<!-- OverLay -->
        <link href="{% static  "overlay/media/stylesheets/font-awesome.css" %}" rel="stylesheet"/>
        <link href="{% static  "overlay/media/stylesheets/main.css" %}" rel="stylesheet"/>       
        <link href="{% static  "overlay/media/stylesheets/shCoreDefault.css" %}" rel="stylesheet"/>        
        <script src="{% static  "overlay/media/javascripts/shCore.js" %}"></script>
        <script src="{% static  "overlay/media/javascripts/shBrushJScript.js" %}"></script>
        <script src="{% static  "overlay/media/javascripts/main.js" %}"></script>
		<script src="{% static  "overlay/jquery.overlay.js" %}"></script>
		
		<!--  NewsFeed -->
		<link href="{% static  "newsfeed/css/site.css" %}" rel="stylesheet"/>
		<link href="http://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet" type="text/css">
		<script src="{% static  "newsfeed/scripts/jquery.bootstrap.newsbox.min.js" %}" type="text/javascript"></script>
		<link href="{% static  "css/poll.css" %}" type="text/css" rel="stylesheet">
<title>Home Page</title>

<div class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<a href="#" class="navbar-brand">Poll</a>
			<button class="navbar-toggle" type="button" data-toggle="collapse"
				data-target="#navbar-main">
				<span class="icon-bar"></span> <span class="icon-bar"></span> <span
					class="icon-bar"></span>
			</button>
		</div>
		<div class="navbar-collapse collapse" id="navbar-main">
			<ul class="nav navbar-nav">
				<li class="dropdown"><a class="dropdown-toggle"
					data-toggle="dropdown" href="#" id="themes">Category <span
						class="caret"></span></a>
					<ul class="dropdown-menu" aria-labelledby="themes">
						<li><a href="#">Mix</a></li>
						<li class="divider"></li>
						<li><a href="#">Sports</a></li>
						<li><a href="#">Shopping</a></li>
						<li><a href="#">Social</a></li>
						<li><a href="#">Entertainment</a></li>
						<li><a href="#">News</a></li>
						<li><a href="#">Politic</a></li>
						<li><a href="#">Fashion</a></li>
					</ul></li>
				<li><a href="#">About</a></li>
				<li><a href="#">How to</a></li>
				<li class="dropdown"><a class="dropdown-toggle"
					data-toggle="dropdown" href="#" id="download">More <span
						class="caret"></span></a>
					<ul class="dropdown-menu" aria-labelledby="download">
						<li><a href="#">More</a></li>
						<li><a href="#">More</a></li>
						<li class="divider"></li>
						<li><a href="#">More</a></li>
						<li><a href="#">More</a></li>
					</ul></li>
			</ul>

			<ul class="nav navbar-nav navbar-right">
				{% if user.is_authenticated %}
				<form class="form col-md-12 center-block" action="account/logout/" method="post">
			 {% csrf_token %}
    			<input type="submit" name="get" class="submit-post" value="Logout" />
			 </form>
				{% else %}
				<li><a href="account/login">Log in</a></li>
				<li><a href="account/signup">Register</a></li> 
				{% endif %}

			 
			</ul>

		</div>
	</div>
</div>
<div class="container">
	
	{% if user.is_authenticated %}
	<!-- Login starts-->
	<div class="container-fluid">
	<div class="row-fluid">
	 <div class="span8">
		 <div class="well"> 
                              
                                  
                                  <form id="poll_form" class="form-horizontal" role="form" name="poll_form" method="" action="">
			 <h4>What's New</h4>
			  <div class="form-group" style="padding:14px;">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text}}
                {{ field }}
            {% endfor %}
            </div>
			<input class="poll_message" type="hidden" autocomplete="off" name="poll_message" value="">
           
            <button id="create_poll" class="btn btn-primary pull-right" type="button">Post</button>
            <ul class="list-inline">
            <li><a href=""><i class="glyphicon glyphicon-upload"></i></a></li>
            <li><a href=""><i class="glyphicon glyphicon-camera"></i></a></li>
            <li><a href=""><i class="glyphicon glyphicon-map-marker"></i></a></li>
            </ul>
        </form>
         <div id="highlight" class="highlight">
        </div>
                                
                          </div>
                          <div id="all_polls">
        {% if latest_poll_list %}
       
    	
    	 
    		{% for poll in latest_poll_list %}
    		
    			<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
    {{poll.created_by}} asked: 
    </h3>
  </div>
  <div class="panel-body">
  <a href="{% url 'polls:detail' poll.id %}">{{ poll.message }}</a>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	
					
						{% csrf_token %}
						{% for option in poll.option_set.all %}
						
						<form id="poll_form" action="{% url 'polls:vote' poll.id %}" method="post">
						{% csrf_token %}
	    				<div id="choice{{ option.id }}">
	    					<div class="vote{{ option.id }}">
	    					{{ option.votes }}
	    					</div>
	    					<div class="option{{ option.id }}">
	    					<input class="poll_vote" type="hidden" autocomplete="off" name="poll_message" value="{{ option.id }}">
	    					<a id={{poll.id}} rel={{ option.id }} class="poll{{poll.id}}option{{ option.id }}" >{{ option.option_text }}</a>
	    					</div>
	    				
	    				
	    				</div>
	    				
						{% endfor %}
						</form>
						
  </div>
  <div class="panel-footer">
  <div class="progress">
  {% for option in poll.option_set.all %}
  <div class="progress-bar-{{ forloop.counter }}" style="width: {{ option.percentage }}%"></div>

  {% endfor %}
</div>
<div class="comment">
comment share
<form id="comment_form" class="form-horizontal" role="form" name="comment_form" method="" action="">
<input class="comment_message"  autocomplete="off" name="comment_message" value="">
<button id="create_poll" class="btn btn-primary pull-right" type="button">Post</button>
</form>
</div>
</div>
</div>
{% endfor %}
{% else %}
    	<p>No polls are available.</p>
		{% endif %}
		<!-- Login ends-->
</div>

  </div>
  <div class="span2">
	<div class="container">
<div class="row">
<div class="col-md-4">
<div class="panel panel-default">
<div class="panel-heading"> <span class="glyphicon glyphicon-list-alt"></span><b>Trending</b></div>
<div class="panel-body">
<div class="row">
<div class="col-xs-12">
<ul class="demo2">
<li class="news-item">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in venenatis enim... <a href="#">Read more...</a></li>
<li class="news-item">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in venenatis enim... <a href="#">Read more...</a></li>
<li class="news-item">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in venenatis enim... <a href="#">Read more...</a></li>
<li class="news-item">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in venenatis enim... <a href="#">Read more...</a></li>
<li class="news-item">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in venenatis enim... <a href="#">Read more...</a></li>
<li class="news-item">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in venenatis enim... <a href="#">Read more...</a></li>
<li class="news-item">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in venenatis enim... <a href="#">Read more...</a></li>
</ul>
</div>
</div>
</div>
<div class="panel-footer"> </div>
</div>
</div>
</div>
</div>
 </div>
</div>		
</div>			
    	
		
	
                              

	{% else %}
		<!-- Logout starts-->
		<div class="jumbotron">
		<h1>Poll</h1>
		<p>Connect with friends #</p>
		<p>Ask questions in a fun way #</p>
		<p>Ask for opinions #</p>
		<p>
			<a class="btn btn-primary btn-lg">Sign up now!</a>
		</p>
		</div>
		<!-- Logout ends-->
	{% endif %}

</div>